### ISSUE TITLE
Errors on website and questions about Elixir's FOSS policy

### ISSUE THREAD

**Issue by ghost** [ProjectElixir-Devices/Wiki#276]
Hi, I have a few questions:

- Is Elixir FOSS? I saw on your website that people have to pay to get the source code. That's not compliant with the licenses AOSP is licensed under. Enlighten me, please.
- There are multiple glaring spelling and grammar mistakes on your website.
- Your CoC seems extremely restrictive, why is it the way it is?

**Comment by manidweep** [comment]
1.Point, its not pure aosp and we have some stuff that is privately owned by the devs of elixir and will be closed for reasons of such
2.if you have valuable feedback regarding that, please point out so and we will correct it 
3.Coc is not restrictive, its a private source rom and as such we may have put some restrictions but the rest of the coc is just as same as other pretty well known roms so we don't see a issue with that
