### ISSUE TITLE
Wrong installation instructions for merlinx

### ISSUE THREAD

**Issue by silacs** [ProjectElixir-Devices/Wiki#96]
it says flash rom first and says format data after that, this should be reverse

**Comment by coderkoala** [comment]
@SystaxError I'm trying to see if I can get my merlin(Note 9) flashes with Project Elixer.

My current FW is essentially V13.0.2(Global), with TWRP(custom - xda forums). How'd I go about flashing the rom on TWRP? The docs are really... "detailed".

**Comment by FunMLG** [comment]
> @SystaxError I'm trying to see if I can get my merlin(Note 9) flashes with Project Elixer.
> 
> My current FW is essentially V13.0.2(Global), with TWRP(custom - xda forums). How'd I go about flashing the rom on TWRP? The docs are really... "detailed".

Installing a custom ROM requires you to have a minimum knowledge of that. Simply put the file on your SD card, then reboot into TWRP, click install and voilà
